// Code generated by zip; DO NOT EDIT.

package utxo

import (
	"fmt"

	zap "github.com/zap-proto/go"
)

// ---- UTXOID ------------------------------------------------------------

const (
	uTXOIDTxIDAt        = 0
	uTXOIDOutputIndexAt = 32
	uTXOIDSymbolAt      = 36
	uTXOIDSize          = 40
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*UTXOID)(nil)

// MarshalZAP writes UTXOID from constant offsets.
func (x *UTXOID) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(uTXOIDSize + 256)
	ob := b.StartObject(uTXOIDSize)
	ob.SetBytesFixed(uTXOIDTxIDAt, x.TxID[:])
	ob.SetUint32(uTXOIDOutputIndexAt, uint32(x.OutputIndex))
	ob.SetBool(uTXOIDSymbolAt, bool(x.Symbol))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads UTXOID out of the buffer that arrived.
func (x *UTXOID) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("UTXOID: %w", err)
	}
	o := m.Root()
	copy(x.TxID[:], o.BytesFixed(uTXOIDTxIDAt, 32))
	x.OutputIndex = uint32(o.Uint32(uTXOIDOutputIndexAt))
	x.Symbol = bool(o.Bool(uTXOIDSymbolAt))
	return nil
}
